CREATE DATABASE MYPROJECT;
USE MYPROJECT;

CREATE TABLE IF NOT EXISTS ECOMMERCE (
INDEX1 INT PRIMARY KEY,
ORDER_DATE DATE NOT NULL,
PRODUCT_NAME VARCHAR(50),
CATEGORY VARCHAR(30),
REGION VARCHAR(10),
QUANTITY INT,
SALES INT,
PROFIT DECIMAL(10,2));
SELECT*FROM ECOMMERCE;


/*“Product Performance & Revenue Analysis”

OBJECTIVE--
✔ Sales Performance
✔ Product Insights
✔ Profitability Analysis
✔ Trend Analysis*/


# TOTAL REVENUE
SELECT SUM(SALES) FROM ECOMMERCE;


# TOTAL PROFIT
SELECT SUM(PROFIT) FROM ECOMMERCE;



# MONTHLY SALES TREND
SELECT
YEAR(ORDER_DATE) AS YEAR,
MONTH(ORDER_DATE) AS MONTH,
SUM(SALES) AS MONTHLY_SALES
FROM ECOMMERCE
GROUP BY YEAR,MONTH
ORDER BY YEAR,MONTH;



# CATEGORY PERFORMANCE
SELECT CATEGORY,
SUM(SALES) AS SALES,
SUM(PROFIT) AS PROFIT
FROM ECOMMERCE
GROUP BY CATEGORY;


# TOP 5 PRODUCTS BY SALES 
SELECT PRODUCT_NAME,
SUM(SALES) AS TOTAL_SALES
FROM ECOMMERCE 
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 5;


# MOST PROFITABLE PRODUCTS(TOP 5)
SELECT PRODUCT_NAME,
SUM(PROFIT) AS TOTAL_PROFIT
FROM ECOMMERCE 
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_PROFIT DESC
LIMIT 5;



# PROFIT MARGIN 
SELECT CATEGORY,
ROUND(SUM(PROFIT) / SUM(SALES) * 100,2) AS PROFIT_MARGIN_PERCENTAGE
FROM ECOMMERCE
GROUP BY CATEGORY;





# GIVE RANKING TO TOP SELLING PRODUCTS
SELECT PRODUCT_NAME,
SUM(SALES) AS TOTAL_SALES,
RANK() OVER (ORDER BY SUM(SALES) DESC) AS SALES_RANK
FROM ECOMMERCE
GROUP BY PRODUCT_NAME;





# CATEGORY SUMMARY AS VIEW
CREATE VIEW category_summary AS
SELECT CATEGORY,
SUM(SALES) AS TOTAL_SALES,
SUM(PROFIT) AS TOTAL_PROFIT
FROM ECOMMERCE
GROUP BY CATEGORY;



CREATE INDEX idx_product_category
ON ECOMMERCE(category);










SELECT CATEGORY,
SUM(SALES) AS TOTAL_SALES
FROM ECOMMERCE 
WHERE SUM(SALES) > ( SELECT CATEGORY,
AVG(SALES) AS TOTAL_SALES
FROM ECOMMERCE
GROUP BY CATEGORY)
GROUP BY CATEGORY;
